title: Transit timing en masse
author: Ekaterina Ivshina & Josh Winn
email: ivshina@princeton.edu
description: TESS transit timing of 278 planets

github_username: transit-timing
# twitter_username:
# facebook_username:
# dribbble_username:

# date_format:

# google_analytics:
# disqus_shortname:

blog_theme: light
# light-theme-accent-color: '#333'
# dark-theme-accent-color: '#eee'

markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
theme: jekyll-theme-minimal
